---
title: পঞ্চগড়ের পথে 
author: Abdullah Al Mahmud
date: '2020-11-22'
slug: roaming-in-panchagarh
categories:
  - roaming
tags:
  - tour
description: ''
thumbnail: ''
---

বৃহস্পতিবার (১৯/১১/২০২০) যাত্রা শুরু। ১২টার পরপর কলেজের গেট দিয়ে বের হলাম। অটোয় চেপে চলে এলাম পাবনা টার্মিনাল। পঞ্চগড়ের ট্রেনের টিকেট কেটেছি নাটোর স্টেশন থেকে। ভাগ্য ভাল, নাটোরের বাস পেয়ে গেলাম।  ঘড়িতে সময় ১২টা ৪৫। ট্রেন ছাড়ার সময় ৩:১৫। শুনেছি বাস নাটোর পৌঁছায় ১ থেকে দেড় ঘণ্টায়। কিন্তু এখানে-সেখানে থামলে কি আর সেটা সম্ভব! 

মেসেজ দিয়ে ট্রেনের অবস্থান জানলাম। নির্ধারিত সময়ের চেয়ে ১৫ মিনিট পিছিয়ে। যাক! একটু স্বস্তি। কিন্তু বাসও যে পিছিয়ে! আবার মেসেজ দেখলাম। ট্রেন পেছানো সময়টুকু পুষিয়ে নিয়েছে। ট্রেন কি তাহলে মিস করব। পৌনে তিনটায় পৌঁছলাম নাটোর শহর। স্টেশন আরও ৪ কি.মি. দূরে। বাস এবার লম্বা বিরতিতে। উপায়ন্তর না দেখে নেমে পড়লাম। অটোয় চেপে স্টেশনে যেতে যেতে ৩টা ০১ বাজে। ট্রেন আগেই চলে এসেছে। ওভারব্রিজ পাড়ি দিয়ে একদম শেষ সময়ে উঠে পড়লাম ট্রেনে। হাঁফ ছেড়ে বাঁচলাম। 

উত্তরবঙ্গের চিরাচরিত সুন্দর ভূদৃশ্য দেখতে দেখতে এগিয়ে চলা। তবে শীত আসি আসি করছে বলে প্রত্যাশার চে একটু কমই সুন্দর চারপাশটা। একে কে নওগাঁ, জয়পুরহাট, দিনাজপুর, ঠাকুরগাঁও পেরিয়ে রাত দশটায় পঞ্চগড় বীর মুক্তিযোদ্ধা সিরাজুল ইসলাম স্টেশনে ট্রেন থামল। নেমে ভ্যানে করে পৌঁছে গেলাম শহরের শেরে বাংলা মোড়ে। এখানেই এইচ. কে. প্যালেচ হোটেলে সিট বুকিং করা। প্রয়োজনীয় ফর্মালিটিজ সেরে রুমে গিয়ে রেস্টুরেন্ট থেকে কিনে আনা খাবার খেয়ে ঘুম। 

সকালে ৮টার দিকে বের হয়ে নাস্তা করলাম নিরব-২ হোটেলে। এবার ভ্যানে চেপে তেঁতুলিয়াগামী বাস স্টপেজে। কয়েক মিনিট পরেই চলে এল বাস। আজকের প্রথম গন্তব্য প্রাচীন মহারাজার দীঘি। বাস থেকে নামলাম বোর্ড অফিস নামক জায়গায়। আবার ভ্যান। পঞ্চগড়ে ভ্যান খুব জনপ্রিয়। এবার পূর্ব দিকে যেতে হবে ৬ কি.মি.। যেতে যেতে উত্তরে তাকাচ্ছি আঁড়চোখে। যদি কাঞ্চনজঙ্গা দেখা যায়। কিন্তু কুয়াশার স্তর ভেদ করে আজ আর তা দেখা যাচ্ছে না। গতকালও সবাই দেখেছে। আফসোস বুকে চেপে পৌঁছে গেলাম ভিতরগড় এলাকায়। এখানেই সেই মহারাজার দীঘি। যেখানে রাজা পৃথু রাজা পরবারসহ আত্মহত্যা করেছিলেন। 

দীঘির পাড় অনেকটা উঁচু। দীঘিটাও বিশাল। পাড়ে উঠে কিছুক্ষণ দীঘির বিশালতা উপভোগ করলাম। ছবিও তুললাম কয়েকখান। এবার পাড় ধরে উত্তরে হাঁটা। চোখে পড়ল সারি সারি চা বাগান। স্যালিলান টি এস্টেটের চা বাগান। দীঘির পাড়ের উত্তর কোণায় কিছুক্ষণ সূর্যের আলো গায়ে মাখিয়ে বসে বসে চা বাগান দেখলাম অপলক নয়নে। 

একটু পরে পাড় থেকে নেমে চা বাগানের আরও কাছে গেলাম। সমতলের চা বাগানের বিশেষ সৌন্দর্যটা এত কাছে না এলে অধরাই থেকে যেত। হাঁটতে হাঁটতে চোখে পড়ল আরও চা বাগান। স্থানীয়রা জানাল, এখন মানুষ ব্যক্তিগতভাবেও প্রচুর চা চাষ করেন। আরেকটু ভালোভাবে দেখতে স্যালিলান টি এস্টেটের একটি বাগানে প্রবেশ করলাম। অসাধারণ দৃশ্য দেখতে দেখতে দীঘির ঘাটে ফিরে আসে। ততক্ষণে জুমার আজান পড়ল। ঘাটের দোকান থেকে ফুচকা খেয়ে নামাজ পড়লাম। 

ভিতরগড়ের প্রাচীন স্থাপনা দেখার ইচ্ছা ছিল। কিন্তু দেখার তেমন কিছু নেই শুনে ফিরতে পথে যাত্রা। এবার অটোয় চেপে আবার বোর্ড অফিস। সেখান থেকে বাসে শহর। বিকেলে ঘুমিয়ে আসরের পর গেলাম করতোয়া নদীর ওপরের ব্রিজে। আবার কাঞ্চনজঙ্গা দেখার বৃথা চেষ্টা। নদীর অনেকটাই শুকিয়ে চৌচির হয়ে আছে। ঘুরে এসে নামলাম নীচেও। 

মাগরিব পড়ে চলে গেলাম দাওয়াত খেতে। ক্যাডেট কলেজের সহকর্মী ও বড় ভাই জাহাঙ্গীর ভাইয়ের চাচার বাসায়। গিয়ে মনেই হলো না, উনারা অন্য কারও না, যেন আমারই চাচা-চাচী। অকৃত্রিম আন্তরিকতায় মুগ্ধ হলাম সন্ধ্যা থেকে রাত ৯টা পর্যন্ত। জাহাঙ্গীর ভাইও একটু পর পর খোঁজ নিচ্ছেন। কোথায় আছি, কেমন আছি, সব ঠিক চলছে কি না ইত্যাদি। আর প্রয়োজনীয় সব পরামর্শ। কোথায় গিয়ে কোন দিকে যাব, কীভাবে যাব আরও কত কী! অনলাইনের যুগে অনলাইন গাইড যাকে বলে! 

পরের দিন ব্যস্ত শিডিউল। পরিকল্পনা করতে করতে ঘুমিয়ে গেলাম। আজ আরও সকাল সকাল নাস্তা সেরে আগের মতোই চলে গেলাম তেঁতুলিয়া বাস স্ট্যান্ডে। আজ গন্তব্য ৫৫ কি. মি. দূরের বাংলাবান্ধা। রাস্তা দারুণ। তেঁতুলিয়ায় ১৫ মিনিট যাত্রাবিরতি দিয়ে বাস চলে এল বাংলাবন্ধা স্থলবন্দর। অটোয় চেপে জিরো পয়েন্ট। বিশাল একটা শূন্য দুই সীমানার মাঝে দাঁড়িয়ে। পাশ দিয়ে এশিয়ান হাইওয়ে চলে গেছে ভারতের শিলিগুড়ির দিকে। 

আবার বাসে করে তেঁতুলিয়া। ভ্যানে চেপে চলে এলাম ডিসি ডাক বাংলোয়। মহানন্দা নদীর তীর ঘেষে দারুণ সাজানো- গোছানো বাংলোটা। বাংলোয় রাত্রিযাপনের চেষ্টা করেছিলাম আগেই। কিন্তু বুকিং দিতে দেরি করে ফেলেছিলাম। কেয়ারটেকারের সাথে কথা বলে জানলাম, আজ রাতে ফাঁকা আছে। তবে কাল সকালে আটটায় ট্রেন। রাতে এখানে থেকে ট্রেন ধরা রিস্কি হয়ে যাবে। 

নদীর পাড়ে বসে থাকলাম কিছুক্ষণ। এখান থেকে কাঞ্চনজঙ্গা ভালো দেখা যাওয়ার কথা। কিন্তু আবহাওয়া আজও খারাপ। এ বছর আর দেখা যাওয়ার সম্ভাবনাই নাই। বাংলোর ভেতরেই দুপুরের খাবার বিক্রি হচ্ছে। দুই প্যাকেট অর্ডার করে রাখলাম। এরপর ভ্যানে উঠে বসলাম কমলা আর চা বাগান দেখব বলে। এই বাগানগুলো বাংলো থেকে দক্ষিণে। দারুণ ভূদৃশ্য দেখতে দেখতে এগিয়ে চলা। একটু পর ভ্যানওয়ালা নিয়ে এল সীমান্তে। ওপাশে শিলিগুড়ি। 